#STEREO CH3 SLAVE 

# # ACQUISITION CONTROL
trigger_source: Line3
trigger_overlap_mode: ReadOut
trigger_selector: FrameStart
enable_trigger: "On"

# # IMAGE FORMAT CONTROL
image_format_color_coding: BayerRG8

# EXPOSURE
exposure_mode: TriggerWidth
#exposure_auto: 'Continuous' 
#auto_exposure_time_upper_limit: 30000.0 # microseconds
#exposure_time: 35000.0 # microseconds

# ROI
# image_format_roi_width: 2048
# image_format_roi_height: 1140
# image_format_y_offset: 760

# auto_exposure_roi_width: 2048
# image_format_roi_height: 1000


# GAIN
# gain_selector: All
auto_gain: 'Off' 
gain: 20.0 # 20

# WHITE BALANCE
#auto_white_balance: "Continuous"
# white_balance_blue_ratio: 0
# white_balance_red_ratio: 1023

# image_format_roi_width: 2048
# image_format_roi_height: 1000

# image_format_x_offset: 0
# image_format_y_offset: 0

# image_format_x_reverse: False
# image_format_y_reverse: False
