#STEREO CH3 MASTER  

# FRAME RATE
acquisition_frame_rate_enable: True
acquisition_frame_rate: 10.0

# DIGITAL I/O FOR TRIGGER
line_selector: Line2
line_mode: Output
line_source: ExposureActive

# IMAGE FORMAT CONTROL
image_format_color_coding: BayerRG8

# EXPOSURE -> Descomentar per sarmiento
exposure_mode: Timed
exposure_auto: 'Continuous' 
auto_exposure_time_upper_limit: 20000.0 # microseconds


# exposure_mode: Timed
# exposure_auto: 'Off' 
# exposure_time: 20000.0 # microseconds

# ROI
# image_format_roi_width: 2048
# image_format_roi_height: 1200
# image_format_x_offset: 0
# image_format_y_offset: 760

# auto_exposure_roi_width: 2048
# auto_exposure_roi_height: 760
# auto_exposure_roi_offset_y: 760

# image_format_x_reverse: True
# image_format_y_reverse: False

# GAIN
# gain_selector: All
auto_gain: 'Off' 
gain: 20.0

# WHITE BALANCE
#auto_white_balance: "Continuous"
# white_balance_blue_ratio: 0
# white_balance_red_ratio: 1023






